import TopHeader from "../components/TopHeader";
import NavHeader from "../components/NavHeader";
import Banner from "../components/Banner";
import Skillscard from "../components/Skillscard";

function Skills(){
    return (
        <>
            <TopHeader></TopHeader>
            <NavHeader></NavHeader>
            <Banner currentPage={'skills'}></Banner>
            <Skillscard icon={'fa-brands fa-html5'} desc={'I have a strong foundation in HTML5, with a focus on writing clean, semantic code that enhances both website accessibility and SEO performance. I am skilled at structuring responsive layouts using modern HTML techniques, ensuring compatibility across devices and screen sizes. I follow web standards to maintain cross-browser consistency, and I am adept at integrating interactive elements such as forms, multimedia, and custom attributes to create engaging user experiences. My expertise extends to combining HTML with CSS, JavaScript, and frameworks like React to build dynamic and functional web pages that provide seamless interactions for users.'} title={'HTML 5'} iconClass={'html1'}></Skillscard>
            <Skillscard icon={'fa-brands fa-css3'} desc={'I am proficient in CSS, with a strong focus on creating responsive, visually appealing, and user-friendly designs. I have a deep understanding of modern CSS techniques such as Flexbox, Grid, and CSS Variables, which allow me to build flexible layouts and handle complex design structures with ease. I am experienced in utilizing CSS preprocessors like Sass to write more maintainable and scalable stylesheets. Additionally, I ensure that my designs are optimized for different screen sizes, making use of media queries to achieve responsive layouts. I am also adept at creating smooth animations, transitions, and hover effects that enhance user interaction and overall website performance.'} title={'CSS 3'} iconClass={'css1'}></Skillscard>
            <Skillscard icon={'fa-brands fa-square-js'} desc={'I possess a strong command of JavaScript, enabling me to build dynamic, interactive web applications. My expertise includes both vanilla JavaScript and working with modern JavaScript features like ES6+ syntax, arrow functions, destructuring, promises, and async/await for cleaner, more efficient code. I am experienced in handling DOM manipulation, event handling, and making asynchronous requests with fetch and AJAX. Additionally, I have worked extensively with libraries and frameworks like React to build interactive UIs, and I am comfortable integrating JavaScript with HTML and CSS to create fully responsive and feature-rich websites. My understanding of functional programming and object-oriented principles helps me write maintainable and scalable code.'} title={'JS'} iconClass={'js1'}></Skillscard>
            <Skillscard icon={'fa-brands fa-react'} desc={'I have hands-on experience with React, a powerful JavaScript library for building dynamic user interfaces. Using React, I create fast, interactive, and scalable web applications by leveraging its component-based architecture and state management capabilities. I am proficient in utilizing React hooks like useState and useEffect to manage state and side effects, as well as React Router for seamless navigation. To improve development speed and optimize performance, I also work with Vite, a modern build tool that offers fast bundling and efficient hot module replacement (HMR). With Vites native support for modern JavaScript and fast refresh, I can quickly iterate on React components while maintaining optimal performance for production builds. This combination of React and Vite allows me to develop high-quality, responsive web applications efficiently.'} title={'REACT + VITE'} iconClass={'react1'}></Skillscard>
        </>
    )
}
export default Skills;